spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/we_chat_order?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
server:
  servlet:
    context-path: /we_chat_order
wechat:
  mpAppId: wxd898fce287jir742
  mpAppSecret: wxd898fce287jir742
  openAppId: wxd898fce287jir742
  openAppSecret: wxd898fce287jir742
  mchId: wxd898fce287jir742
  mchKey: wxd898fce287jir742
  keyPath: wxd898fce287jir742
  notifyUrl: wxd898fce287jir742
  templateId:
    orderStatus: wxd898fce287jir742
projecturl:
  weChatOrder: http://localhost:8080
  weChatMpAuthorize: wxd898fce287jir742
  weChatOpenAuthorize: wxd898fce287jir742
